export default {
  LOGIN: 'LOGIN',
  TABS: 'TABS',
  DASHBOARD: 'DASHBOARD',
  WEATHERDASHBOARDNAVIGATOR: 'HOME',
  WEATHERDASHBOARD: 'WEATHERDASHBOARD',
  WEATHERSEARCHNAVIGATOR: 'SEARCH',
  WEATHERSEARCH: 'WEATHERSEARCH',
  WEATHERDETAILS: 'WEATHERDETAILS',
};
